version: '3.4'

services:
  pdf-merger-user1:
    restart: always
    container_name: pdf-merger-user1
    image: ghcr.io/hopeman876/pdf-duplex-merger:latest
    volumes:
      - "/volume1/Scanner/user1/Doppelseitig:/input"
      - "/volume1/Scanner/user/OCR_machen:/output"
    environment:
      - SOURCE_DIRECTORY=/input
      - DESTINATION_DIRECTORY=/output
      - DELETE_OLD_FILES=True
      - CHECK_INTERVAL=10

  pdf-merger-user2: 
    restart: always
    container_name: pdf-merger-user2
    image: ghcr.io/hopeman876/pdf-duplex-merger:latest
    volumes:
      - "/volume1/Scanner/user2/Doppelseitig:/input"
      - "/volume1/Scanner/user2/OCR_machen:/output"
    environment:
      - SOURCE_DIRECTORY=/input
      - DESTINATION_DIRECTORY=/output
      - DELETE_OLD_FILES=True
      - CHECK_INTERVAL=10
